import { McpServer, createMcpHandler } from "@modelcontextprotocol/server";
import { registerAppResource, registerAppTool, RESOURCE_MIME_TYPE } from "@modelcontextprotocol/ext-apps/server";
import { z } from "zod";

const UI="ui://rasthoria/game-v1.html";
const Score=z.number().int().min(1).max(30);
const Ability=z.object({score:Score,mod:z.number().int().min(-10).max(10)});
const Character=z.object({name:z.string().min(1).max(80),concept:z.string().max(500),past:z.string().max(2000).default(""),level:z.number().int().min(1).max(20).default(1),hp:z.number().int().min(0).max(999),maxHp:z.number().int().min(1).max(999),armor:z.number().int().min(1).max(40),initiative:z.number().int().min(-10).max(20),abilities:z.object({STR:Ability,DEX:Ability,CON:Ability,INT:Ability,WIS:Ability,CHA:Ability}),inventory:z.array(z.string().max(160)).max(50).default([]),conditions:z.array(z.string().max(160)).max(20).default([])});
const Roll=z.object({type:z.enum(["check","dice"]),sides:z.number().int(),reason:z.string(),ability:z.string().nullable().optional(),mode:z.enum(["normal","advantage","disadvantage"]).optional(),rolls:z.array(z.number().int()),kept:z.number().int().optional(),modifier:z.number().int().default(0),dc:z.number().int().optional(),total:z.number().int(),success:z.boolean().optional(),natural20:z.boolean().optional(),natural1:z.boolean().optional()});
const State=z.object({rulesVersion:z.literal("rasthoria-chatgpt-v1").default("rasthoria-chatgpt-v1"),campaignId:z.string(),title:z.string().max(160),premise:z.string().max(5000),genre:z.string().max(120),scene:z.string().max(10000).default(""),location:z.string().max(200).default("Por descubrir"),day:z.number().int().min(1).default(1),time:z.string().max(40).default("08:00"),character:Character,notes:z.array(z.string().max(700)).max(50).default([]),lastRoll:Roll.nullable().default(null),combat:z.any().nullable().default(null)});

const mod=s=>Math.floor((s-10)/2);
function die(s){if(![4,6,8,10,12,20,100].includes(s))throw Error("Dado no admitido");const lim=Math.floor(0x100000000/s)*s,b=new Uint32Array(1);do crypto.getRandomValues(b);while(b[0]>=lim);return b[0]%s+1}
const uniq=a=>[...new Set((a||[]).map(x=>String(x).trim()).filter(Boolean))];
const clone=s=>structuredClone(State.parse(s));
function remove(a,b){const x=new Set((b||[]).map(v=>String(v).toLowerCase()));return a.filter(v=>!x.has(String(v).toLowerCase()))}

const HTML=String.raw`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:dark;--g:#d8ad6a;--c:#f0e2cb}*{box-sizing:border-box}body{margin:0;background:transparent;font-family:Arial;color:#eee}.app{border:1px solid #3c3027;border-radius:16px;overflow:hidden;background:linear-gradient(#131117,#0d0b10)}.top{display:flex;justify-content:space-between;padding:13px 16px;border-bottom:1px solid #302720}.brand{font:600 16px Georgia;letter-spacing:4px;color:#f1d39b}.status{font-size:10px;color:#9c8b76}.grid{display:grid;grid-template-columns:205px 1fr}.sheet{padding:17px;border-right:1px solid #302720}.crumb{font-size:9px;letter-spacing:1.5px;color:#aa8a61;text-transform:uppercase}.name{font:24px Georgia;color:var(--c);margin:5px 0}.concept,.loc{font-size:11px;color:#a9988a}.hp{font-size:11px;margin:14px 0}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.stat{text-align:center;border:1px solid #39323b;border-radius:7px;padding:7px}.stat small{display:block;font-size:7px;color:#978b9f}.stat b{font:17px Georgia;color:#e6c384}.story{padding:18px 22px}.title{font:25px Georgia;color:var(--c);margin:6px 0}.scene{white-space:pre-wrap;font:17px/1.7 Georgia;color:#e8ddce;margin-top:15px}.roll{margin-top:16px;border:1px solid #55412f;border-radius:12px;padding:13px;display:grid;grid-template-columns:88px 1fr;align-items:center;background:#141116}.die{width:78px;height:78px;clip-path:polygon(50% 0,91% 21%,100% 64%,72% 100%,28% 100%,0 64%,9% 21%);display:grid;place-items:center;background:linear-gradient(145deg,#6c5032,#1b1519 55%,#09070a);box-shadow:inset 0 0 0 1px #d5aa68}.num{font:700 31px Georgia;color:#ffe3aa}.roll b{font:21px Georgia;color:#efca90}.roll p{font-size:11px;color:#b8a99a}.empty{padding:30px;text-align:center;color:#988f9a}@media(max-width:620px){.grid{grid-template-columns:1fr}.sheet{border-right:0;border-bottom:1px solid #302720}.scene{font-size:15px}}</style></head><body><div class="app"><div class="top"><div class="brand">RASTHOR·IA</div><div class="status">CHATGPT ES EL NARRADOR</div></div><div id="root" class="empty">Preparando partida…</div></div><script>
const R=document.getElementById('root'),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));function draw(){const d=window.openai?.toolOutput||window.openai?.widgetState?.toolOutput;if(!d?.state){R.textContent='Pídele a ChatGPT que inicie RASTHOR·IA.';return}const s=d.state,c=s.character,r=d.lastRoll||s.lastRoll;R.className='grid';R.innerHTML='<aside class="sheet"><div class="crumb">Tu personaje · Nv. '+E(c.level)+'</div><div class="name">'+E(c.name)+'</div><div class="concept">'+E(c.concept)+'</div><div class="hp">♥ '+E(c.hp)+' / '+E(c.maxHp)+' PG · ARM '+E(c.armor)+'</div><div class="stats">'+Object.entries(c.abilities).map(([k,v])=>'<div class="stat"><small>'+k+'</small><b>'+(v.mod>=0?'+':'')+v.mod+'</b></div>').join('')+'</div></aside><main class="story"><div class="crumb">Crónica de campaña</div><div class="title">'+E(s.title)+'</div><div class="loc">'+E(s.location)+' · Día '+E(s.day)+' · '+E(s.time)+'</div><div class="scene">'+E(s.scene||'ChatGPT todavía no ha narrado la escena.')+'</div>'+(r?'<div class="roll"><div class="die"><span class="num" id="n">?</span></div><div><b>'+E(r.reason)+'</b><p>'+E(r.type==='check'?r.kept+(r.modifier>=0?'+':'')+r.modifier+' = '+r.total+' · DC '+r.dc+' · '+(r.success?'ÉXITO':'FALLO'):(r.rolls||[]).join(' + ')+' = '+r.total)+'</p></div></div>':'')+'</main>';if(r){const n=document.getElementById('n'),f=Number(r.kept??r.total??1),side=Number(r.sides||20),ds=[55,60,70,85,105,135,180,240];let i=0;(function t(){if(i>=ds.length){n.textContent=f;return}n.textContent=1+Math.floor(Math.random()*side);setTimeout(t,ds[i++])})()}}draw();window.addEventListener('message',()=>setTimeout(draw,0));</script></body></html>`;

function server(){
 const s=new McpServer({name:"RASTHOR·IA",version:"1.0.0"});
 registerAppTool(s,"rasthoria_start_campaign",{title:"Iniciar campaña RASTHOR·IA",description:"Crea solo el estado mecánico inicial. ChatGPT es el Narrador y debe escribir la historia. Asigna estadísticas de RPG coherentes con concepto y pasado salvo que el jugador las haya elegido.",inputSchema:z.object({title:z.string().max(160).optional(),premise:z.string().min(1).max(5000),genre:z.string().max(120).optional(),characterName:z.string().min(1).max(80),characterConcept:z.string().max(500),characterPast:z.string().max(2000).default(""),strength:Score,dexterity:Score,constitution:Score,intelligence:Score,wisdom:Score,charisma:Score,inventory:z.array(z.string().max(160)).max(30).default([])}),outputSchema:z.object({state:State,view:z.literal("game")}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},_meta:{ui:{resourceUri:UI},"openai/outputTemplate":UI}},async i=>{const a={STR:{score:i.strength,mod:mod(i.strength)},DEX:{score:i.dexterity,mod:mod(i.dexterity)},CON:{score:i.constitution,mod:mod(i.constitution)},INT:{score:i.intelligence,mod:mod(i.intelligence)},WIS:{score:i.wisdom,mod:mod(i.wisdom)},CHA:{score:i.charisma,mod:mod(i.charisma)}},m=Math.max(6,8+a.CON.mod),state=State.parse({campaignId:crypto.randomUUID(),title:i.title||"Una historia por comenzar",premise:i.premise,genre:i.genre||"Libre",character:{name:i.characterName,concept:i.characterConcept,past:i.characterPast,level:1,hp:m,maxHp:m,armor:10+a.DEX.mod,initiative:a.DEX.mod,abilities:a,inventory:uniq(i.inventory),conditions:[]},notes:[],lastRoll:null,combat:null});return{content:[{type:"text",text:"Estado listo. Narra de inmediato una escena inicial inmersiva de 2–5 párrafos, mete al personaje dentro de la situación sin decidir por él y luego usa rasthoria_apply_state para guardar scene/location."}],structuredContent:{state,view:"game"}}});
 registerAppTool(s,"rasthoria_resolve_check",{title:"Resolver prueba D20",description:"Úsala solo si existe incertidumbre real, riesgo, oposición o dificultad técnica. Nunca inventes el dado.",inputSchema:z.object({state:State,reason:z.string().max(400),ability:z.enum(["STR","DEX","CON","INT","WIS","CHA"]),dc:z.number().int().min(5).max(30),mode:z.enum(["normal","advantage","disadvantage"]).default("normal"),situationalModifier:z.number().int().min(-10).max(10).default(0)}),outputSchema:z.object({state:State,lastRoll:Roll,view:z.literal("roll")}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},_meta:{ui:{resourceUri:UI},"openai/outputTemplate":UI}},async i=>{const st=clone(i.state),rs=[die(20)];if(i.mode!=="normal")rs.push(die(20));const k=i.mode==="advantage"?Math.max(...rs):i.mode==="disadvantage"?Math.min(...rs):rs[0],m=st.character.abilities[i.ability].mod+i.situationalModifier,t=k+m,r=Roll.parse({type:"check",sides:20,reason:i.reason,ability:i.ability,mode:i.mode,rolls:rs,kept:k,modifier:m,dc:i.dc,total:t,success:t>=i.dc,natural20:k===20,natural1:k===1});st.lastRoll=r;return{content:[{type:"text",text:`${i.reason}: ${k}${m>=0?'+':''}${m}=${t} contra DC ${i.dc}: ${r.success?'ÉXITO':'FALLO'}. Narra una consecuencia que haga avanzar la ficción.`}],structuredContent:{state:st,lastRoll:r,view:"roll"}}});
 registerAppTool(s,"rasthoria_roll_dice",{title:"Tirar dados",description:"Tira D4/D6/D8/D10/D12/D20/D100 para daño, tablas o efectos.",inputSchema:z.object({state:State,sides:z.union([z.literal(4),z.literal(6),z.literal(8),z.literal(10),z.literal(12),z.literal(20),z.literal(100)]),count:z.number().int().min(1).max(10).default(1),modifier:z.number().int().min(-100).max(100).default(0),reason:z.string().max(400).default("Tirada")}),outputSchema:z.object({state:State,lastRoll:Roll,view:z.literal("roll")}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},_meta:{ui:{resourceUri:UI},"openai/outputTemplate":UI}},async i=>{const st=clone(i.state),rs=Array.from({length:i.count},()=>die(i.sides)),t=rs.reduce((a,b)=>a+b,0)+i.modifier,r=Roll.parse({type:"dice",sides:i.sides,reason:i.reason,rolls:rs,modifier:i.modifier,total:t});st.lastRoll=r;return{content:[{type:"text",text:`${i.reason}: ${rs.join(' + ')}${i.modifier?` ${i.modifier>0?'+':''}${i.modifier}`:''} = ${t}.`}],structuredContent:{state:st,lastRoll:r,view:"roll"}}});
 registerAppTool(s,"rasthoria_apply_state",{title:"Aplicar consecuencias",description:"Devuelve una copia actualizada del estado; no persiste nada fuera del chat.",inputSchema:z.object({state:State,scene:z.string().max(10000).optional(),location:z.string().max(200).optional(),time:z.string().max(40).optional(),dayDelta:z.number().int().min(-30).max(365).default(0),hpDelta:z.number().int().min(-999).max(999).default(0),addItems:z.array(z.string().max(160)).max(15).default([]),removeItems:z.array(z.string().max(160)).max(15).default([]),addConditions:z.array(z.string().max(160)).max(10).default([]),removeConditions:z.array(z.string().max(160)).max(10).default([]),addNotes:z.array(z.string().max(700)).max(10).default([]),clearLastRoll:z.boolean().default(false)}),outputSchema:z.object({state:State,view:z.literal("game")}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async i=>{const st=clone(i.state);if(i.scene!==undefined)st.scene=i.scene;if(i.location!==undefined)st.location=i.location;if(i.time!==undefined)st.time=i.time;st.day=Math.max(1,st.day+i.dayDelta);st.character.hp=Math.max(0,Math.min(st.character.maxHp,st.character.hp+i.hpDelta));st.character.inventory=uniq(remove(st.character.inventory,i.removeItems).concat(i.addItems));st.character.conditions=uniq(remove(st.character.conditions,i.removeConditions).concat(i.addConditions));st.notes=uniq(st.notes.concat(i.addNotes)).slice(-50);if(i.clearLastRoll)st.lastRoll=null;return{content:[{type:"text",text:"Estado actualizado. Consérvalo como referencia mecánica de la campaña."}],structuredContent:{state:st,view:"game"}}});
 registerAppTool(s,"rasthoria_render",{title:"Mostrar RASTHOR·IA",description:"Renderiza ficha, escena y última tirada dentro de ChatGPT.",inputSchema:z.object({state:State}),outputSchema:z.object({state:State,view:z.literal("game")}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},_meta:{ui:{resourceUri:UI},"openai/outputTemplate":UI}},async({state})=>({content:[{type:"text",text:"Interfaz RASTHOR·IA actualizada."}],structuredContent:{state:State.parse(state),view:"game"}}));
 registerAppResource(s,"RASTHOR·IA",UI,{description:"Ficha y dados de RASTHOR·IA"},async()=>({contents:[{uri:UI,mimeType:RESOURCE_MIME_TYPE,text:HTML,_meta:{ui:{prefersBorder:true}}}]}));
 return s;
}
export const mcpHandler=createMcpHandler(server);
